site_name: Gomqtt
docs_dir: docs


site_url: https://github.com/taitan-org/gomqtt
repo_url: https://github.com/taitan-org/gomqtt.git

site_favicon: favicon.png

site_favicon: favicon.png

markdown_extensions:
    - admonition

pages:
- 主页: index.md

- 技术解密:
   - 架构设计: tech/architecture.md
   - 协议解析: tech/proto.md

- 用户文档:
   - 安装: user-guide/install.md
   - 配置: user-guide/configuration.md
 
- About:
   - Contributing: about/contribute.md
   - Licence: about/license.md
   - Release Notes: about/release-notes.md



copyright: Copyright &copy; 2016 <a href="http://taitan.io">泰坦科技</a>.